export {default as Loader} from './Loader'
export {default as Navbar} from './Navbar'
export {default as Service} from './Service'
export {default as Footer} from './Footer'
export {default as Welcome} from './Welcome'